config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :videos
  resources :users
  resources :sesions

  root 'videos#index'
  get '/signup', to: 'users#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/share-video', to: 'videos#new', as: 'share_video'
  post '/share-video', to: 'videos#create'
  get '*unmatched_route', to: 'application#raise_not_found'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true
end

app/models/video.rb
# frozen_string_literal: true

class Video < ApplicationRecord
  validates :title, presence: true
  validates :shared_by, presence: true
  validates :description, presence: true
  validates :url, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  layout 'application'

  helper_method :current_user, :need_register?, :videos_list
  rescue_from ActiveRecord::RecordNotFound, with: :not_found
  rescue_from Exception, with: :error
  rescue_from ActionController::RoutingError, with: :not_found

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end

  def videos_list
    @videos_list = Video.all
  end

  def need_register?
    @need_register = session[:need_register]
  end

  def raise_not_found
    raise ActionController::RoutingError, "No route matches #{params[:unmatched_route]}"
  end

  def not_found
    respond_to do |format|
      format.html { render file: "#{Rails.root}/public/404.html", layout: false, status: :not_found }
      format.xml { head :not_found }
      format.any { head :not_found }
    end
  end

  def error
    respond_to do |format|
      format.html { render file: "#{Rails.root}/public/500.html", layout: false, status: 500 }
      format.xml { head :not_found }
      format.any { head :not_found }
    end
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  before_action :find_user, only: :create
  before_action :validate_exist, only: :create


  def new
    session[:need_register] = false
  end

  def create
    return unless validate_exist

    if @user&.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      session[:need_register] = false
      redirect_to root_path, flash: { success: 'Login success' }
    else
      session[:need_register] = false
      redirect_to root_path, flash: { danger: 'Invalid email or password' }
    end
  end

  def validate_exist
    unless find_user
      session[:need_register] = false
      redirect_to root_path, flash: { danger: 'User not exist' }
      false
    end
    true
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  def find_user
    @user = User.find_by(email: params[:session][:email])
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :validate_match, only: :create
  before_action :validate_exist, only: :create

  def new
    @user = User.new
  end

  def create
    return unless validate_match
    return unless validate_exist

    @user = User.new(user_create_params)

    if @user&.save
      session[:need_register] = false
      redirect_to root_path, flash: { success: 'Resgister success' }
    else
      session[:need_register] = true
      redirect_to root_path, flash: { danger: 'Invalid email or password' }
    end
  end

  def validate_match
    unless user_params[:password].match?(user_params[:password_confirmation])
      session[:need_register] = true
      redirect_to root_path, flash: { danger: 'Confirmation password not match' }

      false
    end
    true
  end

  def validate_exist
    if User.find_by(email: user_params[:email])
      session[:need_register] = true
      redirect_to root_path, flash: { danger: 'User already exist' }
      false
    end
    true
  end

  private

  def user_create_params
    return unless user_params[:password].match?(user_params[:password_confirmation])

    @user_create_params = {
      email: user_params[:email],
      password: user_params[:password]
    }
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/videos_controller.rb
# frozen_string_literal: true

require 'uri'
class VideosController < ApplicationController
  def index
    @videos = Video.all
  end

  def new
    @video = Video.new
  end

  def create
    return redirect_to new_video_path, flash: { danger: 'Invalid URL' } if video_create_params.nil?

    @video = Video.new(video_create_params)
    @video.save
    respond_to do |format|
      format.html { redirect_to root_path, flash: { success: 'Video was successfully created' } }
    end
  end

  def video_info
    return nil unless valid_url?(video_params[:url])

    @video_info = VideoInfo.new(video_params[:url]) unless video_params[:url].blank?
  end

  private

  def valid_url?(url)
    yts_regexp = %r{^https://(?:www\.)?youtube.com/watch\?(?=[^?]*v=\w+)(?:[^\s?]+)?$}
    yt_regexp = %r{^http://(?:www\.)?youtube.com/watch\?(?=[^?]*v=\w+)(?:[^\s?]+)?$}

    if yts_regexp.match(url) || yt_regexp.match(url)
      true
    else
      false
    end
  end

  def video_create_params
    return if video_info.nil?

    @video_create_params = {
      title: video_info.title,
      shared_by: current_user.email,
      description: video_info.description,
      url: video_params[:url],
      embed_code: video_info.embed_code
    }
  end

  def video_params
    params.require(:video).permit(:url)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/helpers/videos_helper.rb
# frozen_string_literal: true

module VideosHelper
end

app/views/layouts/_message.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name,msg| %>
      <div class='alert alert-<%="#{name}" %>'>
        <%= content_tag :div,msg, :id=>"flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RemiRound2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_importmap_tags %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <%= javascript_include_tag('application.js') %>
  </head>

  <body>
    <nav role="navigation" class="navbar navbar-toggleable-md navbar-expand-md navbar-dark bg-primary">
          <div class="window" style="width: fit-content;">
            <%= link_to "Funny Movies", root_path, class: "navbar-brand", style: "color: white; font-size: 40px;" %>
          </div>
          <div class="window pull-right" style="display: flex; margin-right: 30px; margin-top: 8px; align-items: baseline;">
            <% if current_user.nil? %>
              <% if need_register? %>
                <%= render partial: 'users/form'%>
              <% else %>
                <%= render partial: 'sessions/form'%>
              <% end %>
            <% else %>
              <span style="margin-left: 5px;"> Welcome: <%= current_user&.email %> </span>
              <%= link_to "Share a movie", new_video_path, class: "btn btn-info btn-sm", style: "margin-left: 5px;" %>
              <%= button_to('Log out', logout_path, method: "delete", remote: true, class: "btn btn-info btn-sm", style: "margin-left: 5px;") %>
            <% end %>
          </div>

        <div class="mobile" style="width: 100%;">
          <div class="pull-left">
            <div id="menuToggle">
                <input type="checkbox" />
                  <span></span>
                  <span></span>
                  <span></span>
              <ul id="menu" style="display: grid;">
                <% if current_user.nil? %>
                  <%= link_to "Login", login_path, class: "btn btn-info btn-sm", style: "margin-left: 5px; height: 32px; width: 83px;" %>
                  <%= link_to "Register", signup_path, class: "btn btn-info btn-sm", style: "margin-left: 5px; height: 32px; width: 83px;" %>
                <% else %>
                  <span style="margin-left: 5px; color: #337ab7"> Welcome: <%= current_user&.email %> </span>
                  <%= link_to "Share a movie", new_video_path, class: "btn btn-info btn-sm", style: "margin-left: 5px; height: 32px; width: 83px;" %>
                  <%= button_to('Log out', logout_path, method: "delete", remote: true, class: "btn btn-info btn-sm", style: "margin-left: 5px; height: 32px; width: 83px;") %>
                <% end %>
              </ul>
            </div>
          </div>
          <%= link_to "Funny Movies", root_path, class: "navbar-brand", style: "color: white; font-size: 40px;" %>
        </div>
    </nav>
    <div class="arlert-section" style="width: 100%; height: 62px">
      <% flash.each do |name, msg| %>
        <% if name.match?('success')%>
          <%= content_tag(:div, msg, class: "alert alert-success text-center") %>
        <% else %>
          <%= content_tag(:div, msg, class: "alert alert-danger text-center") %>
        <% end %>
      <% end %>
    </div>
    <%=yield%>
  </body>
</html>

app/views/users/_form.html.erb
<% @user = User.new %>
<%= form_with model: @user, 
  local: true,
  html: {class: "form-inline"} do |f| %>
    <%= f.email_field :email, placeholder: 'Email', class: 'form-control' %>
    <%= f.password_field :password, placeholder: 'Password', class: 'form-control' %>
    <%= f.password_field :password_confirmation, placeholder: 'Confirm password', class: 'form-control' %>
    <%= f.submit 'Register', :class => 'btn btn-info btn-sm' %>
    <%= link_to "Login", root_path(session[:need_register] = nil), class: "btn btn-info btn-sm" %>
<% end %>

app/views/users/_modal.html.erb
<div class="modal fade" tabindex="-1" id="myModal" role="dialog">
  <div class="modal-dialog">
    <%= render 'user/form' %>
  </div>
</div>

app/views/users/new.html.erb
<div class="container border">
  <div class="form-box" style="text-align: center;
    align-items: center;
    display: flex;
    flex-wrap: wrap;
    justify-content: space-evenly;">
    <% @user = User.new %>
    <%= form_with model: @user,
      local: true,
      html: {class: "form-inline", style: "width:80%;"} do |f| %>
        <%= f.email_field :email, placeholder: 'Email', class: 'form-control', style: "margin-bottom:3px;", required: true %>
        <%= f.password_field :password, placeholder: 'Password', class: 'form-control', style: "margin-bottom:3px;", required: true %>
        <%= f.password_field :password_confirmation, placeholder: 'Confirm password', class: 'form-control', style: "margin-bottom:3px;", required: true %>
        <%= f.submit 'Register', :class => 'btn btn-info btn-sm' %>
    <% end %>
  </div>
</div>

app/views/videos/_form.html.erb
<% if video.errors.any? %>
  <%= content_tag(:div, 'A prohibited this video from being saved', class: "alert alert-danger text-center") %>\
<% end %>
<div class="card" style="width: 60%; margin: 0 auto; float: none; margin-bottom: 10px;">
  <div class="card-body">
    <h1 class="card-title text-center">Share a youtube movie</h1>
    <%= form_with(model: video, class: "form-group text-center d-flex align-items-center rgba-black-strong py-5 px-4 justify-content-center")  do |form| %>
      <%= form.text_field :url, class: 'form-control', style: "margin-bottom: 10px;" %>
      <%= form.submit 'Create Video', :class => 'btn btn-info btn-sm' %>
    <% end %>
  </div>
</div>

app/views/videos/_video.html.erb
<div class="card border-primary" style="width: fit-content; margin-bottom: 30px; border-style: solid; padding: 5px; border-radius: 5px; border-color: #337ab7">
  <div class="card-horizontal">
    <div class="img-square-wrapper">
      <%= video.embed_code.html_safe %>
    </div>
    <div class="card-body" style=" margin-left: 20px">
      <h4 class="card-title" style= "overflow: hiden;"> <%= video.title %> </h4>
      <p class="card-text" style= "overflow: hiden;"> <%= video.shared_by %> </p>
      <p class="card-text" style= "overflow: hiden;"> <%= video.description %> </p>
    </div>
  </div>
</div>

app/views/videos/index.html.erb
<div class="container">
  <div class="row align-items-center">
      <% videos_list.each do |video| %>
        <%= render video %>
      <% end %>
  </div>
</div>

app/views/videos/new.html.erb
<div class="container border">
  <div class="row justify-content-center">
    <%= render "form", video: @video %>
  </div>
</div>